# prettier-ignore
version: "3"


services:

  rails:
    container_name: example-rails
    build:
      context: .
      dockerfile: ./docker/rails/Dockerfile
    volumes:
      - ./app:/app
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    container_name: example-db
    build:
      context: .
      dockerfile: ./docker/postgres/Dockerfile
    expose:
      - ${DB_PORT}
    ports:
      - ${DB_PORT_OUT}:${DB_PORT}
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
